### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/anisja.maljm#1]
Hi @AnisjaMaljm,

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Close this ticket.
4. Go to https://github.com/orgs/alptium/teams/java-team/discussions and start doing the practical projects there (see discussions from bottom to top).

Thanks,
Valentina

**Comment by ghost** [comment]
I received this test ticket ☺

**Comment by valentinajemuovic** [comment]
Thanks @AnisjaMaljm :-) Please do now steps 3 & 4.
